### ISSUE TITLE
`fortran-lang/setup-fpm@v6` points towards `v6`, not `v6.0.1`

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/setup-fpm#25]
`- uses: fortran-lang/setup-fpm@v6`

seems to resolve `v6` (causing the CI to fail) instead of the newer version `v6.0.1`, which includes the fix. To solve that, one currently has to specifically use:

`- uses: fortran-lang/setup-fpm@v6.0.1` (see [here](https://github.com/minhqdao/run-f/pull/2), for example).

The reason might be that `v6` was released as [v6](https://github.com/fortran-lang/setup-fpm/releases/tag/v6) instead of `v6.0.0`.

I think the command should always resolve the newest version `>=v6.0.0 <v7.0.0` and therefore the tag `v6` should be deleted and replaced by `v6.0.0`. It won't cause existing workflows to fail.

This would also be in line with major releases of other popular action setups, such as [setup-python](https://github.com/actions/setup-python/releases/tag/v5.0.0) or [node](https://github.com/actions/setup-node/releases/tag/v4.0.0).

@gnikit

**Comment by gnikit** [comment]
This should now be fixed, v6 and v6.0.1 are pointing to the same commit
